# GitHub Actions workflow to add publish artifacts to a GitHub release
# https://docs.github.com/actions/reference/workflow-syntax-for-github-actions
# https://docs.github.com/actions/guides/building-and-testing-python

name: Publish to Release

# Note: on key treated as boolean key by YAML
# https://github.com/adrienverge/yamllint/issues/158#issuecomment-454313233
# However, GitHub Actions documentation is consistent in using it unquoted.
on:   # yamllint disable-line rule:truthy
  # Publish to PyPI when a GitHub release is published
  release:
    types:
    - published

permissions: {}

jobs:
  publish_to_release:
    name: Build publish artifacts, then add to GitHub release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1
      with:
        persist-credentials: false
    - name: Set up .NET
      uses: actions/setup-dotnet@26b0ec14cb23fa6904739307f278c14f94c95bf1  # v5.4.0
      with:
        dotnet-version: latest
    - name: Build publish artifacts
      shell: bash
      env:
        GH_TOKEN: ${{ github.token }}
      # TODO: Publish in parallel:
      # https://github.com/dotnet/sdk/issues/9363#issuecomment-387512008
      run: |
        for arch in x64 arm64; do
          for os in linux osx win; do
            dotnet publish \
              --configuration Release \
              --runtime "$os-$arch" \
              --self-contained true \
              -p:PublishSingleFile=true
          done
        done

        tag_name=${GITHUB_REF#refs/tags/}
        tag_ver_num=${tag_name#v}
        repo_name=${GITHUB_REPOSITORY##*/}
        while IFS=/ read -r framework runtime; do
          publish_zip="$repo_name-$tag_ver_num-$runtime-$framework.zip"
          zip -j -r "$publish_zip" ./*/"bin/Release/$framework/$runtime/publish"
          gh release upload "$tag_name" "$publish_zip"
        done <<FRAMEWORK_RUNTIMES
        $(printf '%s\n' */bin/Release/*/* | cut -d/ -f4- | sort -u)
        FRAMEWORK_RUNTIMES
